name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - main  # Triggers on pushes to main branch

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'
  majorVersion: '1'
  minorVersion: '0'
  patchVersion: '0'

pool:
  name: MyCustomPool  # Your custom pool name
  demands:
    - agent.name -equals MyNewAgent  # Your agent name (exact match)

steps:
  # Install .NET 8 SDK
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      version: $(dotNetVersion)
      performMultiLevelLookup: true

  # Restore NuGet packages
  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      nugetConfigPath: 'NuGet.config'  # Create this if using private feeds

  # Build the solution
  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  # Run tests (if any)
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: 'test'
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --collect:"Code coverage"'

  # Create NuGet package
  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet package'
    inputs:
      command: 'pack'
      packagesToPack: '**/UpperCaseCheckLibrary.csproj'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: $(majorVersion)
      minorVersion: $(minorVersion)
      patchVersion: $(patchVersion)
      configuration: $(buildConfiguration)
      outputDir: '$(Build.ArtifactStagingDirectory)'
      nobuild: true

  # Push to Azure Artifacts
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with Azure Artifacts'

  - task: NuGetCommand@2
    displayName: 'Push to UpperCaseFeed'
    inputs:
      command: 'push'
      feedsToUse: 'select'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'UpperCaseFeed'  # Your feed name
      allowPackageConflicts: true