name: 1.0.0$(Build.BuildId)

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'
  organizationName: 'kpat1045'
  projectName: 'StringLibrary'
  feedName: 'UpperCaseFeed'

stages:
- stage: Build
  jobs:
  - job: BuildAndPack
    pool:
      name: MyCustomPool
      demands:
      - Agent.OS -equals Windows_NT
    steps:
    - checkout: self
      clean: true

    # Simplified feed verification
    - powershell: |
        $feedUrl = "https://pkgs.dev.azure.com/$(organizationName)/$(projectName)/_packaging/$(feedName)/nuget/v3/index.json"
        Write-Host "##[section]Testing feed accessibility: $feedUrl"
        
        # Basic connectivity test
        try {
          $response = Invoke-WebRequest -Uri $feedUrl -UseBasicParsing -Method Head
          Write-Host "##[section]Feed is accessible"
        }
        catch {
          Write-Host "##vso[task.logissue type=error]Failed to access feed: $($_.Exception.Message)"
          Write-Host "##[warning]Please verify:"
          Write-Host "##[warning]1. Feed exists in project $(projectName)"
          Write-Host "##[warning]2. Name is exactly '$(feedName)' (case-sensitive)"
          Write-Host "##[warning]3. Build service has Contributor permissions"
          exit 1
        }
      displayName: 'Verify Feed Accessibility'

    # Install .NET 8
    - task: UseDotNet@2
      displayName: 'Install .NET 8'
      inputs:
        version: $(dotNetVersion)
        performMultiLevelLookup: true

    # Build and pack
    - task: DotNetCoreCLI@2
      displayName: 'Build & Pack'
      inputs:
        command: 'pack'
        projects: 'StringLibrary/StringLibrary.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:Version=$(Build.BuildNumber)'

    # List generated packages (debugging)
    - powershell: |
        Write-Host "##[section]Generated packages:"
        Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Recurse -Filter *.nupkg | ForEach-Object {
          Write-Host $_.FullName
        }
      displayName: 'List Generated Packages'

    # Authenticate with Azure Artifacts
    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'
      inputs:
        forceReinstallCredentialProvider: true

    # Push to feed with explicit credentials
    - powershell: |
        $packagePath = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Filter *.nupkg | Select-Object -First 1 -ExpandProperty FullName
        $feedUrl = "https://pkgs.dev.azure.com/$(organizationName)/$(projectName)/_packaging/$(feedName)/nuget/v3/index.json"
        
        Write-Host "##[section]Pushing package: $packagePath"
        Write-Host "##[section]To feed: $feedUrl"
        
        dotnet nuget push "$packagePath" `
          --source "$feedUrl" `
          --api-key AzureArtifacts `
          --skip-duplicate
      displayName: 'Push to Azure Artifacts'
      env:
        VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_packaging/$(feedName)/nuget/v3/index.json", "username":"$(System.AccessToken)", "password":"$(System.AccessToken)"}]}'

- stage: Test
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: RunTests
    pool:
      name: MyCustomPool
    steps:
    - checkout: self
    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'