name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - main  # Triggers on pushes to main branch

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'
  majorVersion: '1'
  minorVersion: '0'
  patchVersion: '0'

pool:
  name: Default
  demands:
    - agent.name -equals MySelfHostedAgent  # Uses your self-hosted agent

steps:
  # Install .NET 8 SDK
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      version: $(dotNetVersion)

  # Restore NuGet packages
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Build the solution
  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Run tests (if any)
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: 'test'
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'

  # Pack the library into a NuGet package
  - task: DotNetCoreCLI@2
    displayName: 'Create NuGet package'
    inputs:
      command: 'pack'
      packagesToPack: '**/UpperCaseCheckLibrary.csproj'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: $(majorVersion)
      minorVersion: $(minorVersion)
      patchVersion: $(patchVersion)
      configuration: $(buildConfiguration)
      outputDir: '$(Build.ArtifactStagingDirectory)'

  # Authenticate with Azure Artifacts
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with Azure Artifacts'

  # Push the package to Azure Artifacts feed (UpperCaseFeed)
  - task: NuGetCommand@2
    displayName: 'Push to UpperCaseFeed'
    inputs:
      command: 'push'
      feedsToUse: 'select'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'UpperCaseFeed'  # Your Azure Artifacts feed name