name: 1.0.0$(Rev:r)

trigger:
  - main

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'
  solutionPath: '**/*.sln'
  libraryProject: 'StringLibrary\StringLibrary.csproj'  # Windows path

jobs:
- job: Build
  strategy:
    maxParallel: 1  # Ensures single job execution
  pool:
    vmImage: 'windows-latest'
  steps:
    - checkout: self
      clean: true

    - task: UseDotNet@2
      displayName: 'Install .NET 8 SDK'
      inputs:
        version: $(dotNetVersion)

    - powershell: |
        Write-Host "##[section]Project files:"
        Get-ChildItem -Recurse -Filter *.csproj | Select-Object FullName
      displayName: 'Debug: Show files'

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages'
      inputs:
        command: 'restore'
        projects: '$(solutionPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '$(solutionPath)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Pack NuGet package'
      inputs:
        command: 'pack'
        packagesToPack: '$(libraryProject)'
        arguments: '-p:Version=1.0.0 --output $(Build.ArtifactStagingDirectory)'

    - task: NuGetAuthenticate@1
      displayName: 'Authenticate with Azure Artifacts'

    - task: NuGetCommand@2
      displayName: 'Push to Azure Artifacts'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)\**\*.nupkg'
        publishVstsFeed: 'YourProjectName/UpperCaseFeed'